"""add shirt colors

Revision ID: 22625e45d8ef
Revises: bf8003f58c08
Create Date: 2025-10-17 15:19:28.809035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22625e45d8ef'
down_revision = 'bf8003f58c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shirt_colors', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('text_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('text_color')
        batch_op.drop_column('shirt_colors')

    # ### end Alembic commands ###
