"""Add game_pos column to MatchLineup

Revision ID: 6cf7e29e2c74
Revises: 22625e45d8ef
Create Date: 2025-10-20 16:23:12.415631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf7e29e2c74'
down_revision = '22625e45d8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_lineups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_pos', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_lineups', schema=None) as batch_op:
        batch_op.drop_column('game_pos')

    # ### end Alembic commands ###
