"""used home + away

Revision ID: 7b2432f64273
Revises: 86399dcfb4b3
Create Date: 2025-10-22 11:09:21.365741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2432f64273'
down_revision = '86399dcfb4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_home', sa.Boolean(), nullable=False,server_default='false'))
        batch_op.add_column(sa.Column('used_away', sa.Boolean(), nullable=False,server_default='false'))
        batch_op.drop_index(batch_op.f('ix_matches_used'))
        batch_op.create_index(batch_op.f('ix_matches_used_away'), ['used_away'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_used_home'), ['used_home'], unique=False)
        batch_op.drop_column('used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_matches_used_home'))
        batch_op.drop_index(batch_op.f('ix_matches_used_away'))
        batch_op.create_index(batch_op.f('ix_matches_used'), ['used'], unique=False)
        batch_op.drop_column('used_away')
        batch_op.drop_column('used_home')

    # ### end Alembic commands ###
