"""daily games

Revision ID: 86399dcfb4b3
Revises: 6cf7e29e2c74
Create Date: 2025-10-22 00:42:16.477546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86399dcfb4b3'
down_revision = '6cf7e29e2c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_games_date'), ['date'], unique=True)

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', sa.Boolean(), nullable=False,server_default='false'))
        batch_op.create_index(batch_op.f('ix_matches_used'), ['used'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_used'))
        batch_op.drop_column('used')

    with op.batch_alter_table('daily_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_games_date'))

    op.drop_table('daily_games')
    # ### end Alembic commands ###
