"""daily fix

Revision ID: b8ec692bfbc0
Revises: 7b2432f64273
Create Date: 2025-10-22 11:22:53.719308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ec692bfbc0'
down_revision = '7b2432f64273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_team_side', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_games', schema=None) as batch_op:
        batch_op.drop_column('target_team_side')

    # ### end Alembic commands ###
