"""Add jersey_number to MatchLineup and MatchSubs

Revision ID: fff5fbb4eb61
Revises: 
Create Date: 2025-10-14 17:50:34.672601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff5fbb4eb61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_lineups', sa.Column('jersey_number', sa.String(length=50), nullable=True))
    op.add_column('match_subs', sa.Column('jersey_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_subs', 'jersey_number')
    op.drop_column('match_lineups', 'jersey_number')
    
    # ### end Alembic commands ###
